In [1]:
import pandas as pd
df=pd.read_csv("train_data.csv")
df

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584104,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-10-20,0.730019,0.270275,0.027992,1.000707,0.009055,0.062496,0.007465,0.009124,...,NaN,NaN,NaN,0.007318,0.001905,0.008018,NaN,0.000643,0.006883,0.005218
584105,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-11-25,0.844972,0.441578,0.016751,1.000803,0.006895,0.065446,0.005221,0.000781,...,NaN,NaN,NaN,0.007419,0.003857,0.002067,NaN,0.007332,0.006067,0.000796
584106,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-12-02,0.847738,0.008786,0.019621,1.001376,0.002343,0.063035,0.002726,0.000431,...,NaN,NaN,NaN,0.004099,0.003209,0.008518,NaN,0.002199,0.007600,0.004834
584107,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2018-01-25,0.799988,0.420666,0.068999,1.009913,0.000960,0.023186,0.004820,0.009395,...,NaN,NaN,NaN,0.003611,0.001086,0.006518,NaN,0.002883,0.009805,0.009545
584108,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2018-02-11,0.807755,0.091016,0.051410,1.006029,0.004556,0.015180,0.009476,0.007273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.isnull().sum()

customer_ID         0
S_2                 0
P_2              4829
D_39                0
B_1                 0
                ...
D_141           10502
D_142          483700
D_143           10502
D_144            4305
D_145           10502
Length: 190, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584109 entries, 0 to 584108
Columns: 190 entries, customer_ID to D_145
dtypes: float64(186), object(4)
memory usage: 846.7+ MB

In [8]:
df = df.sort_values(['customer_ID', 'S_2'])
df

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_141,D_142,D_143,D_144,D_145,util_1,util_2,util_3,capacity_left_1,capacity_left_2
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,0.003818,NaN,0.000569,0.000610,0.002674,0.008665,0.001847,0.004677,0.998114,0.936735
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,0.005032,NaN,0.009576,0.005492,0.009217,0.004920,0.006166,0.002712,0.995730,0.930889
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,0.000427,NaN,0.003429,0.006986,0.002603,0.021447,0.095898,0.009332,0.988018,0.862675
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,0.003200,NaN,0.008419,0.006527,0.009600,0.013646,0.002556,0.005516,0.989017,0.957928
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,0.008889,NaN,0.001670,0.008126,0.009827,0.015182,0.002621,0.009305,0.985534,0.944765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584104,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-10-20,0.730019,0.270275,0.027992,1.000707,0.009055,0.062496,0.007465,0.009124,...,0.008018,NaN,0.000643,0.006883,0.005218,0.027972,0.370225,0.009117,0.972715,0.459744
584105,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-11-25,0.844972,0.441578,0.016751,1.000803,0.006895,0.065446,0.005221,0.000781,...,0.002067,NaN,0.007332,0.006067,0.000796,0.016738,0.522589,0.000781,0.984052,0.403394
584106,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2017-12-02,0.847738,0.008786,0.019621,1.001376,0.002343,0.063035,0.002726,0.000431,...,0.008518,NaN,0.002199,0.007600,0.004834,0.019594,0.010364,0.000430,0.981754,0.838952
584107,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2018-01-25,0.799988,0.420666,0.068999,1.009913,0.000960,0.023186,0.004820,0.009395,...,0.006518,NaN,0.002883,0.009805,0.009545,0.068321,0.525833,0.009302,0.940915,0.379322
584108,1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6...,2018-02-11,0.807755,0.091016,0.051410,1.006029,0.004556,0.015180,0.009476,0.007273,...,NaN,NaN,NaN,NaN,NaN,0.051101,0.112677,0.007229,0.954619,0.716739

In [10]:
##Create Utilization (Ratio) Features
df['util_1'] = df['B_1'] / (df['B_2'] + 1e-5)
df['util_2'] = df['D_39'] / (df['P_2'] + 1e-5)
df['util_3'] = df['B_3'] / (df['B_2'] + 1e-5)

In [7]:
##Creating  capacity features
df['capacity_left_1'] = df['B_2'] - df['B_1']
df['capacity_left_2'] = df['P_2'] - df['D_39']

In [12]:
##Adding behaviour and customer level
df['util_1_diff'] = df.groupby('customer_ID')['util_1'].diff()

In [17]:
final_df = df.groupby('customer_ID').agg({
    'util_1': ['mean', 'max'],
    'util_2': ['mean'],
    'capacity_left_1': ['mean'],
    'util_1_diff': ['mean']
})

In [16]:
final_df = final_df.fillna(0)
final_df

                                                      util_1             \
                                                        mean        max
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.011942   0.021447
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.025632   0.109087
00001b22f846c82c51f6e3958ccd81970162bae8b007e80...  0.005375   0.012326
000041bdba6ecadd89a52d11886e8eaaec9325906c97233...  0.062895   0.278769
00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8ad...  0.007296   0.012056
...                                                      ...        ...
1b29c70baf0b1ae8304fa41038b32d7ef1f428339c6b425...  0.031246   0.062151
1b2a0e1667d1f3944c5450ff34a7a23fd0c355b77fa5bee...  7.675439  53.783112
1b2a23a9bb39cf5cc49465b2a1459af7ea1f3c80054dc20...  0.600407   4.000509
1b2a3eccdf8ab13822041e6b7eb1738ab07256e9dff6d6d...  2.418605  15.386930
1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6e...  0.027009   0.068321

                                                      util_2 capacity_left_1  \
                                                        mean            mean
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.011296        0.993079
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.239374        0.965429
00001b22f846c82c51f6e3958ccd81970162bae8b007e80...  0.004763        0.811291
000041bdba6ecadd89a52d11886e8eaaec9325906c97233...  0.084541        0.895388
00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8ad...  0.005154        0.808602
...                                                      ...             ...
1b29c70baf0b1ae8304fa41038b32d7ef1f428339c6b425...  0.514321        0.974322
1b2a0e1667d1f3944c5450ff34a7a23fd0c355b77fa5bee...  0.676267        0.276571
1b2a23a9bb39cf5cc49465b2a1459af7ea1f3c80054dc20...  0.242240        0.830598
1b2a3eccdf8ab13822041e6b7eb1738ab07256e9dff6d6d...  0.625138        0.423353
1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6e...  0.141901        0.977291

                                                   util_1_diff
                                                          mean
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...    0.000054
00000fd6641609c6ece5454664794f0340ad84dddce9a26...    0.000736
00001b22f846c82c51f6e3958ccd81970162bae8b007e80...    0.000288
000041bdba6ecadd89a52d11886e8eaaec9325906c97233...   -0.006175
00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8ad...    0.000435
...                                                        ...
1b29c70baf0b1ae8304fa41038b32d7ef1f428339c6b425...   -0.001228
1b2a0e1667d1f3944c5450ff34a7a23fd0c355b77fa5bee...   -2.123192
1b2a23a9bb39cf5cc49465b2a1459af7ea1f3c80054dc20...    0.662257
1b2a3eccdf8ab13822041e6b7eb1738ab07256e9dff6d6d...    1.280554
1b2a4ffb01d7f0224876255859722cf7e0da3ac3fd34e6e...    0.003273

[48439 rows x 5 columns]